import type { SponsorTier } from './runtime/shared/types'

export type SponsorsMode = 'runtime' | 'prerender' | 'client'

export const DEFAULT_TOKEN_ENV = 'NUXT_GITHUB_SPONSORS_TOKEN'

/** Every consumer site uses these two keys, so they are the defaults. */
export const DEFAULT_TIERS: SponsorTier[] = [
  { key: 'top', minimumMonthlyDollars: 50 },
  { key: 'gold', minimumMonthlyDollars: 25 },
]

export type SponsorTokenResult
  = { _tag: 'ok', token: string }
    | { _tag: 'missing', tokenEnv: string }

export type SponsorDeliveryPlan
  = { _tag: 'runtime' }
    | { _tag: 'client' }
    | { _tag: 'prerender' }
    | { _tag: 'prerender-skipped', warning: string }

/**
 * A fine-grained GitHub token cannot call the GraphQL API, so sites alias the
 * sponsors token to another secret. `tokenEnv` names that secret directly.
 */
export function resolveSponsorToken(env: Record<string, string | undefined>, tokenEnv: string): SponsorTokenResult {
  const token = env[tokenEnv]?.trim()
  return token ? { _tag: 'ok', token } : { _tag: 'missing', tokenEnv }
}

export function planSponsorDelivery(mode: SponsorsMode, token: SponsorTokenResult): SponsorDeliveryPlan {
  if (mode !== 'prerender')
    return { _tag: mode }
  if (token._tag === 'ok')
    return { _tag: 'prerender' }
  return {
    _tag: 'prerender-skipped',
    warning: `No sponsors token in ${token.tokenEnv} at build time. The route is not prerendered, because a prerender would bake an empty sponsor list into the deploy.`,
  }
}

export function normalizeRoute(value = '/api/github-sponsors'): string {
  const route = value.trim()
  if (!route.startsWith('/'))
    throw new TypeError('githubSponsors.route must start with /')
  return route.replace(/\/$/, '') || '/'
}

/**
 * The tiers a build runs with. The fallback lives here rather than in the module
 * `defaults`, because Nuxt merges those with `defu`, which joins arrays instead of
 * replacing them. See the note on `defaults` in module.ts.
 */
export function resolveSponsorTiers(input: SponsorTier[] | undefined): SponsorTier[] {
  return parseSponsorTiers(input ?? DEFAULT_TIERS)
}

export function parseSponsorTiers(input: SponsorTier[]): SponsorTier[] {
  const keys = new Set<string>()
  return input.map((tier) => {
    const key = tier.key.trim()
    if (!key || keys.has(key))
      throw new TypeError('githubSponsors.tiers must have unique, non-empty keys')
    if (!Number.isFinite(tier.minimumMonthlyDollars) || tier.minimumMonthlyDollars < 0)
      throw new TypeError(`githubSponsors tier ${key} must have a non-negative minimum`)
    keys.add(key)
    return { key, minimumMonthlyDollars: tier.minimumMonthlyDollars }
  }).toSorted((a, b) => b.minimumMonthlyDollars - a.minimumMonthlyDollars)
}

export function renderSponsorTierAugmentation(tiers: readonly SponsorTier[]): string {
  return [
    '// Generated by @harlan-zw/nuxt-github-sponsors. Do not edit.',
    `declare module '@harlan-zw/nuxt-github-sponsors/types' {`,
    '  interface ConfiguredSponsorTiers {',
    ...tiers.map(tier => `    ${JSON.stringify(tier.key)}: true`),
    '  }',
    '}',
    '',
    'export {}',
    '',
  ].join('\n')
}
