import { mkdir, mkdtemp, readdir, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { prepareCloudflareBindingTypes } from '../src/binding-types'

const mocks = vi.hoisted(() => ({
  generateTypes: vi.fn(),
}))

vi.mock('wrangler', () => ({
  experimental_generateTypes: mocks.generateTypes,
}))

describe('cloudflare binding type cache', () => {
  beforeEach(() => {
    mocks.generateTypes.mockReset()
    mocks.generateTypes.mockImplementation(async ({ config, path }) => {
      const content = `// Generated by Wrangler by running \`wrangler types --config=${config} ${path}\` (hash: mockhash)\ndeclare global { interface CloudflareBindings { DB: D1Database } }\n`
      await mkdir(dirname(path), { recursive: true })
      await writeFile(path, content)
      return {
        content,
        env: 'interface __BaseEnv_CloudflareBindings {\n  DB: D1Database;\n}',
        runtime: 'declare namespace Cloudflare {}\n',
      }
    })
  })

  afterEach(() => {
    vi.unstubAllEnvs()
  })

  it('reuses one portable entry across worktrees and materializes private outputs', async () => {
    const root = await mkdtemp(join(tmpdir(), 'nuxt-cloudflare-binding-cache-'))
    const cacheDir = join(root, 'shared-cache')
    const firstRoot = join(root, 'worktree-a')
    const secondRoot = join(root, 'worktree-b')
    const common = {
      cacheDir,
      compatibilityDate: '2026-08-27',
      nodeCompat: true,
    }

    try {
      const first = await prepareCloudflareBindingTypes({
        ...common,
        buildDir: join(firstRoot, '.nuxt'),
        rootDir: firstRoot,
        wrangler: {
          kv_namespaces: [{ binding: 'CACHE', id: 'shared-id' }],
          vars: { ZEBRA: 'last', ALPHA: 'first' },
        },
      })
      const second = await prepareCloudflareBindingTypes({
        ...common,
        buildDir: join(secondRoot, '.nuxt'),
        rootDir: secondRoot,
        wrangler: {
          vars: { ALPHA: 'first', ZEBRA: 'last' },
          kv_namespaces: [{ binding: 'CACHE', id: 'shared-id' }],
        },
      })

      expect(mocks.generateTypes).toHaveBeenCalledTimes(1)
      expect(second).toEqual(first)
      expect(second.content).not.toContain(firstRoot)
      expect(second.content).not.toContain(secondRoot)
      expect(await readFile(join(secondRoot, '.nuxt/types/cloudflare-bindings.d.ts'), 'utf8')).toBe(second.content)
      expect(JSON.parse(await readFile(join(secondRoot, '.nuxt/nuxt-cloudflare/wrangler.json'), 'utf8'))).toMatchObject({
        kv_namespaces: [{ binding: 'CACHE', id: 'shared-id' }],
      })
      expect(await readdir(cacheDir)).toHaveLength(1)
    }
    finally {
      await rm(root, { force: true, recursive: true })
    }
  })

  it('shares the default cache outside each worktree', async () => {
    const root = await mkdtemp(join(tmpdir(), 'nuxt-cloudflare-binding-cache-'))
    const cacheHome = join(root, 'cache-home')
    vi.stubEnv('XDG_CACHE_HOME', cacheHome)
    const prepare = (name: string) => prepareCloudflareBindingTypes({
      buildDir: join(root, name, '.nuxt'),
      compatibilityDate: '2026-08-27',
      nodeCompat: true,
      rootDir: join(root, name),
      wrangler: {},
    })

    try {
      await prepare('worktree-a')
      await prepare('worktree-b')

      expect(mocks.generateTypes).toHaveBeenCalledTimes(1)
      expect(await readdir(join(cacheHome, 'nuxt-cloudflare/binding-types'))).toHaveLength(1)
    }
    finally {
      await rm(root, { force: true, recursive: true })
    }
  })

  it('rebuilds a corrupt entry and reports why it was rejected', async () => {
    const root = await mkdtemp(join(tmpdir(), 'nuxt-cloudflare-binding-cache-'))
    const cacheDir = join(root, 'shared-cache')
    const reasons: string[] = []
    const prepare = (name: string) => prepareCloudflareBindingTypes({
      buildDir: join(root, name, '.nuxt'),
      cacheDir,
      compatibilityDate: '2026-08-27',
      nodeCompat: true,
      onCacheInvalid: reason => reasons.push(reason),
      rootDir: join(root, name),
      wrangler: {},
    })

    try {
      await prepare('worktree-a')
      const [entry] = await readdir(cacheDir)
      await writeFile(join(cacheDir, entry!), '{')

      await prepare('worktree-b')

      expect(mocks.generateTypes).toHaveBeenCalledTimes(2)
      expect(reasons).toHaveLength(1)
      expect(reasons[0]).toContain('JSON cannot be parsed')
      expect(JSON.parse(await readFile(join(cacheDir, entry!), 'utf8'))).toMatchObject({ schema: 1 })
    }
    finally {
      await rm(root, { force: true, recursive: true })
    }
  })

  it('invalidates the entry when the compatibility date changes', async () => {
    const root = await mkdtemp(join(tmpdir(), 'nuxt-cloudflare-binding-cache-'))
    const cacheDir = join(root, 'shared-cache')
    const prepare = (name: string, compatibilityDate: string) => prepareCloudflareBindingTypes({
      buildDir: join(root, name, '.nuxt'),
      cacheDir,
      compatibilityDate,
      nodeCompat: true,
      rootDir: join(root, name),
      wrangler: {},
    })

    try {
      await prepare('worktree-a', '2026-08-26')
      await prepare('worktree-b', '2026-08-27')

      expect(mocks.generateTypes).toHaveBeenCalledTimes(2)
      expect(await readdir(cacheDir)).toHaveLength(2)
    }
    finally {
      await rm(root, { force: true, recursive: true })
    }
  })

  it('can disable the shared cache', async () => {
    const root = await mkdtemp(join(tmpdir(), 'nuxt-cloudflare-binding-cache-'))
    const prepare = (name: string) => prepareCloudflareBindingTypes({
      buildDir: join(root, name, '.nuxt'),
      cacheDir: false,
      compatibilityDate: '2026-08-27',
      nodeCompat: true,
      rootDir: join(root, name),
      wrangler: {},
    })

    try {
      await prepare('worktree-a')
      await prepare('worktree-b')

      expect(mocks.generateTypes).toHaveBeenCalledTimes(2)
    }
    finally {
      await rm(root, { force: true, recursive: true })
    }
  })

  it('leaves one readable entry after concurrent misses', async () => {
    const root = await mkdtemp(join(tmpdir(), 'nuxt-cloudflare-binding-cache-'))
    const cacheDir = join(root, 'shared-cache')
    const prepare = (name: string) => prepareCloudflareBindingTypes({
      buildDir: join(root, name, '.nuxt'),
      cacheDir,
      compatibilityDate: '2026-08-27',
      nodeCompat: true,
      rootDir: join(root, name),
      wrangler: {},
    })

    try {
      const [first, second] = await Promise.all([
        prepare('worktree-a'),
        prepare('worktree-b'),
      ])
      const generatedCalls = mocks.generateTypes.mock.calls.length
      const [entry] = await readdir(cacheDir)

      expect(second).toEqual(first)
      expect(JSON.parse(await readFile(join(cacheDir, entry!), 'utf8'))).toMatchObject({ schema: 1 })
      await prepare('worktree-c')
      expect(mocks.generateTypes).toHaveBeenCalledTimes(generatedCalls)
      expect(await readdir(cacheDir)).toEqual([entry])
    }
    finally {
      await rm(root, { force: true, recursive: true })
    }
  })
})
