catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - tinyexec@1.2.2

catalog:
  '@vitest/coverage-v8': 4.1.7
  drizzle-orm: 0.45.2
  unbuild: ^3.6.1
  wrangler: ^4.94.0

catalogs:
  dev-build:
    '@types/node': ^25.9.1
    typescript: ^6.0.3
    vue-tsc: ^3.3.1
  dev-test:
    happy-dom: ^20.9.0
    vitest: ^4.1.7
  nuxt:
    '@nuxt/kit': ^4.4.6
    '@nuxt/module-builder': ^1.0.2
    '@nuxt/schema': ^4.4.6
    nuxt: ^4.4.6
  vue:
    vue: ^3.5.34

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - vue-demi

trustPolicyIgnoreAfter: 262800

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  vue-demi: true
  workerd: true
