catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - playground

catalog:
  '@vitest/coverage-v8': 4.1.8
  '@vueuse/core': ^14.3.0
  bumpp: ^11.1.0
  consola: ^3.4.2
  eslint-plugin-harlanzw: ^0.17.0
  nitropack: ^2.13.4
  nuxt: ^4.4.8
  oxc-parser: 0.135.0
  oxc-walker: 1.0.0
  pathe: ^2.0.3
  unbuild: ^3.6.1
  zod: 4.4.3

catalogs:
  dev-build:
    '@arethetypeswrong/cli': ^0.18.3
    typescript: ^6.0.3
    vue-tsc: ^3.3.4
  dev-lint:
    '@antfu/eslint-config': ^9.0.0
    eslint: ^10.5.0
  dev-test:
    '@nuxt/test-utils': ^4.0.3
    '@vue/test-utils': ^2.4.11
    happy-dom: ^20.10.3
    vitest: ^4.1.8
  nuxt:
    '@nuxt/kit': ^4.4.8
    '@nuxt/module-builder': ^1.0.2
    '@nuxt/schema': ^4.4.8
    nuxt: ^4.4.6
  vue:
    vue: ^3.5.38
    vue-router: ^5.1.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - vue-demi

trustPolicyIgnoreAfter: 262800

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  vue-demi: true
  workerd: true
