catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - tinyexec@1.2.2

catalog:
  '@antfu/eslint-config': ^9.1.0
  '@nuxt/test-utils': ^4.0.3
  '@vitest/coverage-v8': 4.1.9
  citty: ^0.2.2
  drizzle-orm: 1.0.0-rc.3
  eslint: ^10.6.0
  eslint-plugin-harlanzw: latest
  eslint-plugin-vue: latest
  h3: 2.0.1-rc.22
  magicast: ^0.5.3
  nitropack: ^2.13.4
  unbuild: ^3.6.1
  wrangler: ^4.105.0

catalogs:
  dev-build:
    '@types/node': ^26.0.1
    typescript: ^6.0.3
    vue-tsc: ^3.3.5
  dev-test:
    happy-dom: ^20.10.6
    vitest: ^4.1.9
  nuxt:
    '@nuxt/kit': ^4.4.8
    '@nuxt/module-builder': ^1.0.2
    '@nuxt/schema': ^4.4.8
    nuxt: ^4.4.8
  vue:
    vue: ^3.5.39

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - vue-demi

trustPolicyIgnoreAfter: 262800

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  vue-demi: true
  workerd: true
