import type { WranglerConfigInput } from './wrangler'
import { createHash, randomUUID } from 'node:crypto'
import { mkdir, readFile, rename, unlink, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { homedir } from 'node:os'
import process from 'node:process'
import { dirname, resolve } from 'pathe'
import { readAuthoredWranglerConfig } from './wrangler-file'

interface BindingTypeGenerationOptions {
  buildDir: string
  cacheDir?: false | string
  compatibilityDate?: string
  config: WranglerConfigInput
  nodeCompat: boolean
  onCacheInvalid?: (reason: string) => void
}

export interface CloudflareBindingTypeArtifact {
  content: string
  signature: string
}

interface PreparedBindingTypeGenerationOptions extends Omit<BindingTypeGenerationOptions, 'config'> {
  rootDir: string
  wrangler: WranglerConfigInput
}

type BindingTypeCacheRead
  = | { _tag: 'hit', artifact: CloudflareBindingTypeArtifact }
    | { _tag: 'invalid', reason: string }
    | { _tag: 'missing' }

interface BindingTypeCacheEntry {
  schema: 1
  artifactHash: string
  content: string
  signature: string
}

type FileWrite
  = | { _tag: 'failed', error: unknown }
    | { _tag: 'written' }

const BINDING_TYPE_CACHE_SCHEMA = 1
const require = createRequire(import.meta.url)

const COMPUTED_WRANGLER_KEYS = new Set([
  'configPath',
  'definedEnvironments',
  'targetEnvironment',
  'topLevelName',
  'userConfigPath',
])

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error)
}

function isNodeError(error: unknown, code: string): boolean {
  return error instanceof Error && 'code' in error && error.code === code
}

function hash(value: string): string {
  return createHash('sha256').update(value).digest('hex')
}

function stableValue(value: unknown): unknown {
  if (Array.isArray(value))
    return value.map(stableValue)
  if (!isRecord(value))
    return value
  return Object.fromEntries(
    Object.entries(value)
      .sort(([left], [right]) => compareText(left, right))
      .map(([key, child]) => [key, stableValue(child)]),
  )
}

function mergeDefaults(primary: unknown, fallback: unknown): unknown {
  if (primary === undefined || primary === null)
    return fallback
  if (Array.isArray(primary) && Array.isArray(fallback))
    return [...primary, ...fallback]
  if (!isRecord(primary) || !isRecord(fallback))
    return primary

  const merged: Record<string, unknown> = { ...primary }
  for (const [key, value] of Object.entries(fallback))
    merged[key] = mergeDefaults(merged[key], value)
  return merged
}

function normalizeConfig(config: WranglerConfigInput, options: BindingTypeGenerationOptions): WranglerConfigInput {
  const normalized = Object.fromEntries(
    Object.entries(config).filter(([key, value]) => !COMPUTED_WRANGLER_KEYS.has(key) && value !== undefined),
  ) as WranglerConfigInput
  delete normalized.main

  normalized.assets = mergeDefaults({ binding: 'ASSETS', directory: '.' }, normalized.assets) as WranglerConfigInput['assets']
  normalized.compatibility_date ??= options.compatibilityDate

  if (options.nodeCompat) {
    const flags = new Set(normalized.compatibility_flags ?? [])
    if (flags.has('nodejs_compat_v2') && flags.has('no_nodejs_compat_v2'))
      flags.delete('nodejs_compat_v2')
    if (!flags.has('nodejs_compat_v2')) {
      flags.add('nodejs_compat')
      flags.add('no_nodejs_compat_v2')
    }
    normalized.compatibility_flags = [...flags]
  }

  return normalized
}

function compareText(left: string, right: string): number {
  if (left < right)
    return -1
  if (left > right)
    return 1
  return 0
}

function canonicalizeBindingEnvironment(environment: string): string {
  return environment
    .replaceAll('\r\n', '\n')
    .replace(
      /(interface __BaseEnv_CloudflareBindings \{\n)([\s\S]*?)(\n\})/,
      (_, opening: string, members: string, closing: string) => [
        opening,
        members.split('\n').sort((left, right) => compareText(left.trim(), right.trim())).join('\n'),
        closing,
      ].join(''),
    )
    .replace(
      /Pick<Cloudflare\.Env,([^>]+)>/g,
      (_, members: string) => `Pick<Cloudflare.Env, ${members.split('|').map(member => member.trim()).sort(compareText).join(' | ')}>`,
    )
}

function createBindingTypeSignature(environment: string, runtime: string): string {
  return hash(`${canonicalizeBindingEnvironment(environment)}\0${runtime.replaceAll('\r\n', '\n')}`)
}

function normalizeGeneratedContent(content: string): string {
  return content.replace(
    /^\/\/ Generated by Wrangler by running `.*` \(hash: ([a-zA-Z0-9]+)\)$/m,
    '// Generated by Wrangler by running `wrangler types` (hash: $1)',
  )
}

function reportInvalidCache(reason: string, report?: (reason: string) => void): void {
  if (report) {
    report(reason)
    return
  }
  process.emitWarning(`[nuxt-cloudflare] Binding type cache entry is invalid: ${reason}. Rebuilding it.`)
}

function parseCacheEntry(source: string): BindingTypeCacheRead {
  let value: unknown
  try {
    value = JSON.parse(source)
  }
  catch (error) {
    return { _tag: 'invalid', reason: `JSON cannot be parsed: ${errorMessage(error)}` }
  }
  if (!isRecord(value))
    return { _tag: 'invalid', reason: 'the entry must be an object' }
  if (value.schema !== BINDING_TYPE_CACHE_SCHEMA)
    return { _tag: 'invalid', reason: `schema ${String(value.schema)} is unsupported` }
  if (typeof value.content !== 'string')
    return { _tag: 'invalid', reason: 'content must be a string' }
  if (typeof value.signature !== 'string' || !/^[a-f0-9]{64}$/.test(value.signature))
    return { _tag: 'invalid', reason: 'signature must be a SHA-256 hash' }
  if (typeof value.artifactHash !== 'string' || value.artifactHash !== hash(`${value.content}\0${value.signature}`))
    return { _tag: 'invalid', reason: 'the artifact hash does not match' }
  return {
    _tag: 'hit',
    artifact: { content: value.content, signature: value.signature },
  }
}

async function readCacheEntry(path: string): Promise<BindingTypeCacheRead> {
  const source = await readFile(path, 'utf8')
    .then(value => ({ _tag: 'read' as const, value }))
    .catch((error: unknown) => isNodeError(error, 'ENOENT')
      ? { _tag: 'missing' as const }
      : { _tag: 'failed' as const, error })
  if (source._tag === 'missing')
    return { _tag: 'missing' }
  if (source._tag === 'failed')
    return { _tag: 'invalid', reason: `the entry cannot be read: ${errorMessage(source.error)}` }
  return parseCacheEntry(source.value)
}

function cacheEntry(artifact: CloudflareBindingTypeArtifact): BindingTypeCacheEntry {
  return {
    schema: BINDING_TYPE_CACHE_SCHEMA,
    artifactHash: hash(`${artifact.content}\0${artifact.signature}`),
    content: artifact.content,
    signature: artifact.signature,
  }
}

function artifactsMatch(left: CloudflareBindingTypeArtifact, right: CloudflareBindingTypeArtifact): boolean {
  return left.content === right.content && left.signature === right.signature
}

async function removeTemporaryFile(path: string): Promise<unknown | undefined> {
  return unlink(path)
    .then(() => undefined)
    // Another writer cannot use this unique path. ENOENT only means the rename completed.
    .catch((error: unknown) => isNodeError(error, 'ENOENT') ? undefined : error)
}

async function writeCacheEntry(path: string, artifact: CloudflareBindingTypeArtifact): Promise<void> {
  const temporaryPath = `${path}.${process.pid}.${randomUUID()}.tmp`
  await writeFile(temporaryPath, `${JSON.stringify(cacheEntry(artifact))}\n`, { flag: 'wx', mode: 0o600 })
  const write = await rename(temporaryPath, path)
    .then((): FileWrite => ({ _tag: 'written' }))
    .catch((error: unknown): FileWrite => ({ _tag: 'failed', error }))
  if (write._tag === 'written')
    return

  const [existing, cleanupError] = await Promise.all([
    readCacheEntry(path),
    removeTemporaryFile(temporaryPath),
  ])
  if (cleanupError)
    throw new AggregateError([write.error, cleanupError], 'Binding type cache write and cleanup failed.')
  if (existing._tag === 'hit' && artifactsMatch(existing.artifact, artifact))
    return
  throw write.error
}

async function readWranglerVersion(): Promise<string> {
  const packagePath = require.resolve('wrangler/package.json')
  const source = await readFile(packagePath, 'utf8')
  const parsed = parseCachePackage(source)
  if (parsed._tag === 'invalid')
    throw new Error(`[nuxt-cloudflare] Wrangler package metadata is invalid: ${parsed.reason}`)
  return parsed.version
}

function parseCachePackage(source: string): { _tag: 'valid', version: string } | { _tag: 'invalid', reason: string } {
  let value: unknown
  try {
    value = JSON.parse(source)
  }
  catch (error) {
    return { _tag: 'invalid', reason: `JSON cannot be parsed: ${errorMessage(error)}` }
  }
  if (!isRecord(value) || typeof value.version !== 'string' || value.version.length === 0)
    return { _tag: 'invalid', reason: 'version must be a non-empty string' }
  return { _tag: 'valid', version: value.version }
}

function defaultCacheDir(): string {
  return resolve(process.env.XDG_CACHE_HOME || resolve(homedir(), '.cache'), 'nuxt-cloudflare/binding-types')
}

function resolveCacheDir(options: PreparedBindingTypeGenerationOptions): false | string {
  if (options.cacheDir === false)
    return false
  return options.cacheDir ? resolve(options.rootDir, options.cacheDir) : defaultCacheDir()
}

function cacheKey(config: WranglerConfigInput, wranglerVersion: string): string {
  return hash(JSON.stringify({
    config: stableValue(config),
    schema: BINDING_TYPE_CACHE_SCHEMA,
    wranglerVersion,
  }))
}

function readAuthoredConfig(rootDir: string): WranglerConfigInput {
  const authored = readAuthoredWranglerConfig(rootDir)
  if (authored._tag === 'invalid')
    throw new SyntaxError(`Invalid Wrangler config "${authored.path}": ${authored.reason}`)
  return authored._tag === 'authored' ? authored.config : {}
}

async function generateCloudflareBindingTypes(
  options: BindingTypeGenerationOptions,
): Promise<CloudflareBindingTypeArtifact> {
  const directory = resolve(options.buildDir, 'nuxt-cloudflare')
  const configPath = resolve(directory, 'wrangler.json')
  const typePath = resolve(options.buildDir, 'types/cloudflare-bindings.d.ts')
  const config = normalizeConfig(options.config, options)
  await Promise.all([
    mkdir(directory, { recursive: true }),
    mkdir(dirname(typePath), { recursive: true }),
  ])
  await writeFile(configPath, `${JSON.stringify(config, null, 2)}\n`)

  const cacheDir = options.cacheDir
  const cachePath = cacheDir
    ? resolve(cacheDir, `${cacheKey(config, await readWranglerVersion())}.json`)
    : undefined
  if (cachePath) {
    const cached = await readCacheEntry(cachePath)
    if (cached._tag === 'hit') {
      await writeFile(typePath, cached.artifact.content)
      return cached.artifact
    }
    if (cached._tag === 'invalid')
      reportInvalidCache(cached.reason, options.onCacheInvalid)
  }

  const { experimental_generateTypes } = await import('wrangler')
  const generated = await experimental_generateTypes({
    config: configPath,
    envInterface: 'CloudflareBindings',
    includeRuntime: true,
    path: typePath,
    strictVars: false,
  })
  if (!generated.env || !generated.runtime)
    throw new Error('[nuxt-cloudflare] Wrangler did not generate Cloudflare binding and runtime types.')

  const artifact = {
    content: normalizeGeneratedContent(generated.content),
    signature: createBindingTypeSignature(generated.env, generated.runtime),
  }
  await writeFile(typePath, artifact.content)
  if (cachePath && cacheDir) {
    await mkdir(cacheDir, { recursive: true, mode: 0o700 })
    await writeCacheEntry(cachePath, artifact)
  }
  return artifact
}

export async function prepareCloudflareBindingTypes(
  options: PreparedBindingTypeGenerationOptions,
): Promise<CloudflareBindingTypeArtifact> {
  const authored = readAuthoredConfig(options.rootDir)
  const config = mergeDefaults(options.wrangler, authored) as WranglerConfigInput
  return generateCloudflareBindingTypes({ ...options, cacheDir: resolveCacheDir(options), config })
}

export async function assertCloudflareBindingTypesCurrent(
  options: BindingTypeGenerationOptions & { expectedSignature: string },
): Promise<void> {
  const generated = await generateCloudflareBindingTypes(options)
  if (generated.signature !== options.expectedSignature) {
    throw new Error(
      '[nuxt-cloudflare] Generated binding types differ from the final Wrangler config. Run `nuxt prepare` and review binding configuration order.',
    )
  }
}
