catalogMode: prefer
cleanupUnusedCatalogs: true
minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@5.20260715.1'
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - tinyexec@1.2.2

catalog:
  '@antfu/eslint-config': ^9.2.0
  '@cloudflare/workers-types': ^5.20260723.1
  '@nuxt/test-utils': ^4.0.3
  '@vitest/coverage-v8': 4.1.10
  citty: ^0.2.2
  drizzle-orm: 1.0.0-rc.4
  eslint: ^10.7.0
  eslint-plugin-harlanzw: ^0.17.1
  eslint-plugin-vue: ^10.10.0
  h3: 2.0.1-rc.25
  magicast: ^0.5.3
  nitropack: ^2.13.4
  nuxt: ^4.5.0
  unbuild: ^3.6.1
  wrangler: ^4.113.0

catalogs:
  dev-build:
    '@types/node': ^26.1.1
    typescript: ^6.0.3
    vue-tsc: ^3.3.8
  dev-test:
    happy-dom: ^20.11.1
    vitest: ^4.1.10
  nuxt:
    '@nuxt/kit': ^4.5.0
    '@nuxt/module-builder': ^1.0.2
    '@nuxt/schema': ^4.5.0
  vue:
    vue: ^3.5.40

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - vue-demi

trustPolicyIgnoreAfter: 262800

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  vue-demi: true
  workerd: true
