# repository | labels | warm | max | cpus | memory-reservation | memory-limit | memory-swap

harlan-zw/nuxtseo.com|harlan-desktop-deploy,nuxtseo-deploy|0|1|12|13g|16g|20g
harlan-zw/nuxtseo.com|harlan-desktop-ci,nuxtseo-ci|0|4|8|5g|9g|11g
harlan-zw/nuxtseo.com|harlan-desktop-light|0|6|2|1g|2g|3g
harlan-zw/gscdump.com|harlan-desktop-ci|0|4|4|4g|8g|10g
harlan-zw/mdream.dev|harlan-desktop-ci|0|3|4|4g|8g|10g
harlan-zw/zhead.dev|harlan-desktop-ci|0|3|4|3g|6g|8g
harlan-zw/scripts.nuxt.com|harlan-desktop-ci|0|2|4|3g|6g|8g
harlan-zw/hogwild.harlanzw.com|harlan-desktop-ci|0|2|2|1g|2g|3g
harlan-zw/hogwild.harlanzw.com|harlan-desktop-deploy|0|1|2|1g|2g|3g
skilld-dev/skilld.dev|harlan-desktop-ci|0|4|4|4g|7g|9g
skilld-dev/skilld.dev|harlan-desktop-deploy|0|1|4|5g|7g|9g

harlan-zw/eslint-worker-pool|harlan-desktop-ci|0|2|8|2g|4g|5g
harlan-zw/gscdump|harlan-desktop-ci|0|2|4|3g|5g|6g
harlan-zw/massivemonster.com|harlan-desktop-ci|0|2|8|3g|6g|8g
harlan-zw/nuxt-audit|harlan-desktop-ci|0|2|4|2g|4g|5g
harlan-zw/ripast|harlan-desktop-ci|0|2|2|1g|2g|3g
harlan-zw/nuxt-ai-kit|harlan-desktop-ci|0|2|4|3g|5g|6g
harlan-zw/gscdump.com|harlan-desktop-deploy|0|1|8|10g|12g|14g
