# repository | labels | warm | max | cpus | memory | memory-swap

harlan-zw/nuxtseo.com|harlan-desktop-deploy,nuxtseo-deploy|0|1|12|16g|20g
harlan-zw/nuxtseo.com|harlan-desktop-ci,nuxtseo-ci|0|4|8|9g|11g
harlan-zw/nuxtseo.com|harlan-desktop-light|0|6|2|2g|3g
harlan-zw/gscdump.com|harlan-desktop-ci|0|4|4|8g|10g
harlan-zw/mdream.dev|harlan-desktop-ci|0|3|4|6g|8g
harlan-zw/zhead.dev|harlan-desktop-ci|0|3|4|6g|8g
harlan-zw/scripts.nuxt.com|harlan-desktop-ci|0|2|4|6g|8g
harlan-zw/hogwild-status|harlan-desktop-ci|0|2|2|2g|3g
harlan-zw/hogwild-status|harlan-desktop-deploy|0|1|2|2g|3g
skilld-dev/skilld.dev|harlan-desktop-ci|0|4|4|7g|9g
