import { describe, expect, it } from 'vitest'

describe('subpath exports', () => {
  it('loads direct runtime entrypoints', async () => {
    const query = await import('@harlan-zw/nuxt-use-query/query')
    const mutation = await import('@harlan-zw/nuxt-use-query/mutation')
    const rpc = await import('@harlan-zw/nuxt-use-query/rpc')
    const subscription = await import('@harlan-zw/nuxt-use-query/subscription')
    const websocket = await import('@harlan-zw/nuxt-use-query/websocket')
    const telemetry = await import('@harlan-zw/nuxt-use-query/telemetry')
    const queryCache = await import('@harlan-zw/nuxt-use-query/query-cache')
    const cache = await import('@harlan-zw/nuxt-use-query/cache')

    expect(query.useNuxtQuery).toBeTypeOf('function')
    expect(mutation.useNuxtMutation).toBeTypeOf('function')
    expect(rpc.defineNuxtRpcQuery).toBeTypeOf('function')
    expect(rpc.createNuxtRpcClient).toBeTypeOf('function')
    expect(rpc.invalidateNuxtRpc).toBeTypeOf('function')
    expect('resolveNuxtRpcQueryRequest' in rpc).toBe(false)
    expect('serializeCanonicalJson' in rpc).toBe(false)
    expect(subscription.useNuxtSubscription).toBeTypeOf('function')
    expect(subscription.createSubscriptionController).toBeTypeOf('function')
    expect(websocket.nuxtWebSocketSource).toBeTypeOf('function')
    expect(telemetry.NUXT_USE_QUERY_TELEMETRY_HOOKS.queryFinish).toBe('nuxt-use-query:telemetry:query:finish')
    expect(queryCache.invalidateNuxtQueries).toBeTypeOf('function')
    expect(queryCache.removeNuxtQueries).toBeTypeOf('function')
    expect('seedCacheFromPayload' in queryCache).toBe(false)
    expect('serializeQueryCacheToPayload' in queryCache).toBe(false)
    expect(cache.createQueryCache).toBeTypeOf('function')
  })
})
