import type { SettleBatchMemberOptions } from '../batch'
import type { ReconcileTerminalFailureContextFactory } from '../reconcile-terminal'
import { resolveCloudflareBindings } from '@harlan-zw/nuxt-cloudflare/bindings'
import { useRuntimeConfig } from 'nitropack/runtime'
// @ts-expect-error - #cf-jobs/app is the generated registry alias, resolved by Nuxt
import { jobRegistry } from '#cf-jobs/app'
// @ts-expect-error - generated by the Nuxt module from cfJobs.reconcile.terminalFailureContext
import { createReconcileJobContext } from '#cf-jobs/reconcile-context'
import { createD1DurableBatchStore, recoverOrphanedBatches, settleBatchMember } from '../batch'
import { createD1DurableJobRepository } from '../d1'
import { findD1Binding } from '../dev-worker'
import { createQueuePublisher, enqueueDurableJob, prepareDurableJob } from '../outbox'
import { runTerminalizedJobFailure } from '../reconcile-terminal'
import { recoverDurableJobs } from '../recovery'
import { defineScheduledTask } from '../scheduled'

// cf-jobs recovery backstop (the "app's own reconcile cron" the durable-queue
// runtime documents as required). Two failure modes leave a durable job stranded
// with no queue message to re-trigger it, and nothing else recovers them:
//
//   1. A consumer reserves a job, then the isolate is recycled / hits a limit
//      before it completes or releases → the row stays `reserved` forever.
//   2. `onFinish` / a release path persists a follow-up row but the queue send is
//      skipped (no binding) or throws → the row is `ready` but undispatched.
//
// This task reclaims (1) via `releaseStaleReservedDurableJobs`, lets the original
// Cloudflare redelivery win during a short grace, then sweeps any row still due.
// Module-owned so every consuming app gets the backstop without copying it.
//
// Resilient by construction: every early-out returns a tagged skip rather than
// throwing, so a missing binding in one env can't crash the cron.
interface ReconcileRuntimeConfig {
  cfJobs?: {
    queues?: Record<string, { binding?: string } | string>
    reconcile?: {
      d1Binding?: string
      staleSeconds?: number
      orphanedSeconds?: number
      redeliveryGraceSeconds?: number
      orphanedBatchSeconds?: number
      limit?: number
    }
  }
}

// Run a trivial query to confirm a binding is a real, working D1 — an RPC stub
// (Durable Object / service binding) duck-types as D1 but throws `The RPC
// receiver does not implement the method "prepare"` when actually invoked.
async function probeD1(db: unknown): Promise<boolean> {
  try {
    await (db as { prepare: (sql: string) => { first: () => Promise<unknown> } }).prepare('SELECT 1').first()
    return true
  }
  catch {
    return false
  }
}

export default defineScheduledTask({
  name: 'cf-jobs:reconcile',
  // Every 2 minutes — fast enough that a stranded job (e.g. a batch member whose
  // onFinish assessment never dispatched) recovers well within a user's session.
  cron: '*/2 * * * *',
  description: 'cf-jobs recovery backstop: reclaim stale-reserved jobs + re-dispatch orphaned ready jobs',
  async run() {
    const env = resolveCloudflareBindings<Record<string, unknown>>()
    if (!env)
      return { result: { skipped: 'no-env' as const } }

    const rc = useRuntimeConfig() as ReconcileRuntimeConfig
    const reconcile = rc.cfJobs?.reconcile ?? {}

    let d1 = findD1Binding(env, reconcile.d1Binding)
    if (!d1)
      return { result: { skipped: 'no-d1-binding' as const } }

    // `findD1Binding` duck-types `prepare`/`exec`, which an RPC stub (a Durable
    // Object / service binding on the `cloudflare-durable` preset) also satisfies
    // — but invoking `.prepare()` on a stub throws `The RPC receiver does not
    // implement the method`. This bit even the PINNED path: a pinned binding name
    // that resolves to a stub in the task context was trusted unprobed, so
    // reconcile silently `recovery-error`'d every tick. So ALWAYS probe the
    // resolved binding (pinned or scanned); if it fails, scan every binding and
    // pick the first that answers a trivial query.
    if (!(await probeD1(d1.db))) {
      let working: { binding: string, db: typeof d1.db } | undefined
      for (const [name, value] of Object.entries(env as Record<string, unknown>)) {
        if (value && typeof (value as { prepare?: unknown }).prepare === 'function' && await probeD1(value)) {
          working = { binding: name, db: value as typeof d1.db }
          break
        }
      }
      if (!working) {
        console.warn(
          `[cf-jobs:reconcile] D1 binding "${d1.binding}" failed a probe (likely an RPC stub in this task context) and no other binding answered — skipping. Pin a real D1 via cfJobs.reconcile.d1Binding.`,
        )
        return { result: { skipped: 'no-working-d1-binding' as const } }
      }
      if (working.binding !== d1.binding)
        console.warn(`[cf-jobs:reconcile] D1 binding "${d1.binding}" failed a probe; using "${working.binding}".`)
      d1 = working
    }

    const queues = rc.cfJobs?.queues ?? {}
    const repo = createD1DurableJobRepository(d1.db)
    const store = createD1DurableBatchStore(d1.db)
    // Map a job's logical queue → its env binding name. `queues[q]` is either the
    // binding string or the enriched `{ binding, ... }` object (prod path).
    const publisher = createQueuePublisher(env, (queue: string) => {
      const entry = queues[queue]
      return typeof entry === 'string' ? entry : entry?.binding
    }, {
      // A missing/stub queue producer binding (no `.send` in this task context)
      // would otherwise drop re-dispatches silently — surface it loudly so a
      // swept-but-not-dispatched tick is diagnosable.
      onMissingBinding: (queue, count) =>
        console.warn(`[cf-jobs:reconcile] no working queue producer binding for "${queue}" — ${count} message(s) NOT dispatched (binding missing or lacks .send here).`),
    })

    const staleSeconds = reconcile.staleSeconds ?? 300
    const orphanedSeconds = reconcile.orphanedSeconds ?? 600
    const redeliveryGraceSeconds = reconcile.redeliveryGraceSeconds ?? 120
    const orphanedBatchSeconds = reconcile.orphanedBatchSeconds ?? 7 * 86400
    const limit = reconcile.limit ?? 100
    const nowSeconds = Math.floor(Date.now() / 1000)

    // The task fires every 2 minutes; a D1/queue failure here must not surface as
    // a recurring unhandled worker exception (Sentry noise, red tail). Degrade to
    // a tagged skip + one warning so a misconfigured env is visible but inert.
    try {
      const dispatchOnFinish: NonNullable<SettleBatchMemberOptions['dispatchOnFinish']> = async ({ continuation, batch }) => {
        const record = await prepareDurableJob({
          name: continuation.name,
          payload: continuation.payload,
          registry: jobRegistry,
          delaySeconds: continuation.delaySeconds,
        })
        const result = await enqueueDurableJob(
          repo,
          publisher,
          record,
          continuation.delaySeconds ? { delaySeconds: continuation.delaySeconds } : undefined,
        )
        if (result.status !== 'enqueued' && result.status !== 'duplicate') {
          console.warn(
            `[cf-jobs:reconcile] recovered batch "${batch.id}" onFinish "${continuation.name}" persisted but was not dispatched: ${result.status}`,
          )
        }
      }
      const recovered = await recoverDurableJobs(repo, publisher, {
        now: nowSeconds,
        staleSeconds,
        orphanedSeconds,
        redeliveryGraceSeconds,
        limit,
        staleError: 'stale-reservation',
        onTerminalized: async (jobs) => {
          for (const job of jobs) {
            await runTerminalizedJobFailure({
              env,
              registry: jobRegistry,
              terminalized: job,
              createContext: createReconcileJobContext as ReconcileTerminalFailureContextFactory<Record<string, unknown>, unknown, unknown> | undefined,
            }).then((result) => {
              if (result._tag === 'context-unavailable') {
                console.error(
                  `[cf-jobs:reconcile] terminalized stale job "${job.id}" (${job.jobType}) but cannot run definition.failed without cfJobs.reconcile.terminalFailureContext. Durable evidence remains in failed_jobs.`,
                )
              }
            }).catch((error) => {
              console.error(
                `[cf-jobs:reconcile] terminalized stale job "${job.id}" (${job.jobType}) but definition.failed could not complete. Durable evidence remains in failed_jobs.`,
                error,
              )
            })
            await settleBatchMember({
              store,
              jobId: job.id,
              failed: true,
              dispatchOnFinish,
            }).catch((error) => {
              console.warn(
                `[cf-jobs:reconcile] terminalized job "${job.id}" but failed to settle its batch: ${(error as Error)?.message ?? error}`,
              )
            })
          }
        },
      })
      const orphanedBatches = await recoverOrphanedBatches({
        store,
        before: recovered.terminalized > 0 ? nowSeconds : nowSeconds - orphanedBatchSeconds,
        now: nowSeconds,
        limit,
        dispatchOnFinish,
      })

      const result = {
        released: recovered.released,
        terminalized: recovered.terminalized,
        terminalizedJobIds: recovered.terminalizedJobs.slice(0, 10).map(job => job.id),
        swept: recovered.swept,
        dispatched: recovered.dispatched,
        orphanedBatches: orphanedBatches.recovered,
        orphanedBatchScanned: orphanedBatches.scanned,
        orphanedBatchSkipped: orphanedBatches.skipped,
        orphanedBatchOnFinishDispatched: orphanedBatches.onFinishDispatched,
        orphanedBatchOnFinishFailed: orphanedBatches.onFinishFailed,
        orphanedBatchUnrecoverable: orphanedBatches.unrecoverable,
      }
      for (const error of orphanedBatches.errors) {
        console.warn(
          `[cf-jobs:reconcile] recovered orphaned batch "${error.batchId}" but failed to dispatch onFinish: ${(error.error as Error)?.message ?? error.error}`,
        )
      }
      if (orphanedBatches.unrecoverable > 0) {
        const ids = orphanedBatches.unrecoverableBatches.slice(0, 10).map(batch => batch.id).join(', ')
        console.warn(
          `[cf-jobs:reconcile] ${orphanedBatches.unrecoverable} orphaned batch(es) have no active members but missing terminal evidence; left pending: ${ids}`,
        )
      }
      // Surface a tick that actually did (or should have done) work, so a
      // recovering backlog — or a swept-but-not-dispatched stall — is visible in
      // logs instead of hiding in the (un-logged) task return value.
      if (result.swept > 0 || result.released > 0 || result.terminalized > 0 || result.orphanedBatches > 0 || result.orphanedBatchScanned > 0 || result.orphanedBatchUnrecoverable > 0)
        console.warn(`[cf-jobs:reconcile] ${JSON.stringify(result)}`)
      return { result }
    }
    catch (error) {
      console.warn(`[cf-jobs:reconcile] recovery failed on binding "${d1.binding}": ${(error as Error)?.message ?? error}`)
      return { result: { skipped: 'recovery-error' as const } }
    }
  },
})
