/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 44c9de74beea5b3c1d1d096bdf3bd247)
interface __BaseEnv_Env {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.output/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
