import type { ModuleOptions } from './types'
import { existsSync } from 'node:fs'
import { relative, resolve } from 'node:path'
import { addTemplate, createResolver, defineNuxtModule, resolveFiles, updateTemplates } from '@nuxt/kit'

export type { ModuleOptions } from './types'

declare module '@nuxt/schema' {
  interface RuntimeConfig {
    cfJobs: ModuleOptions
  }
}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: 'nuxt-cf-jobs',
    configKey: 'cfJobs',
  },
  defaults: {
    queues: {},
    jobsDir: 'server/jobs',
    jobsPattern: '**/*.ts',
    jobsIgnore: ['**/_*.ts', '**/*.d.ts', '**/*.test.ts', '**/*.spec.ts'],
    registryAlias: '#cf-jobs/app',
    orphanedJobThresholdSeconds: 600,
  },
  setup(options, nuxt) {
    const resolver = createResolver(import.meta.url)

    nuxt.options.alias['#cf-jobs/server'] = resolver.resolve('./runtime/server')
    const registryTemplate = addTemplate({
      filename: 'cf-jobs/registry.ts',
      write: true,
      getContents: async () => generateRegistryTemplate(options, nuxt.options.rootDir, resolve(nuxt.options.buildDir, 'cf-jobs')),
    })
    nuxt.options.alias[options.registryAlias ?? '#cf-jobs/app'] = registryTemplate.dst

    nuxt.hooks.hook('builder:watch' as never, (async (_event: string, path: string) => {
      if (!isWatchedJobPath(path, options, nuxt.options.rootDir))
        return
      await updateTemplates({ filter: template => template.dst === registryTemplate.dst })
    }) as never)

    nuxt.options.runtimeConfig.cfJobs = {
      ...options,
      ...(nuxt.options.runtimeConfig.cfJobs ?? {}),
    }
  },
})

async function generateRegistryTemplate(options: ModuleOptions, rootDir: string, templateDir: string): Promise<string> {
  const files = await resolveJobFiles(options, rootDir)
  const imports = files.map((file, index) => {
    return `import job${index} from ${JSON.stringify(toImportPath(templateDir, file))}`
  })
  const loaders = files.map((file) => {
    return `  ${JSON.stringify(toJobName(file, options, rootDir))}: () => import(${JSON.stringify(toImportPath(templateDir, file))}).then(m => m.default),`
  })
  const jobItems = files.map((_, index) => `job${index}`).join(', ')

  return [
    '/* This file is generated by nuxt-cf-jobs. Do not edit directly. */',
    `import { assertJobQueueBindings, createJobQueue, defineJobRegistry, prepareRegisteredDurableJob, validateJobQueueBindings } from '#cf-jobs/server'`,
    `import { useRuntimeConfig } from '#imports'`,
    `import type { JobDefinitionsByNameOfLoaders, JobMessageByName, JobMessageByQueue, JobNameOf, JobPayloadByName, JobPayloadOf, JobQueueByName, QueueNameOf, PrepareRegisteredDurableJobOptions, QueueSource } from '#cf-jobs/server'`,
    ...imports,
    '',
    'export const jobLoaders = {',
    ...loaders,
    '} as const',
    `export const jobs = [${jobItems}] as const`,
    'export const jobRegistry = defineJobRegistry(jobs)',
    '',
    'export type Jobs = typeof jobs',
    'export type JobsByName = JobDefinitionsByNameOfLoaders<typeof jobLoaders>',
    'export type JobName = keyof JobsByName & JobNameOf<Jobs>',
    'export type JobDefinitionOf<Name extends JobName> = JobsByName[Name]',
    'export type QueueName = QueueNameOf<Jobs>',
    'export type JobPayload<Name extends JobName> = JobPayloadOf<JobDefinitionOf<Name>>',
    'export type JobQueue<Name extends JobName> = JobQueueByName<Jobs, Name>',
    'export type JobMessage<Name extends JobName> = JobMessageByName<Jobs, Name>',
    'export type QueueMessage<Queue extends QueueName> = JobMessageByQueue<Jobs, Queue>',
    '',
    'export const getHandler = jobRegistry.getHandler',
    'export const getJobDefinition = jobRegistry.getJobDefinition',
    'export const getJobQueue = jobRegistry.getJobQueue',
    'export const getJobRoute = jobRegistry.getJobRoute',
    'export const validateRegistry = jobRegistry.validate',
    'export const validateQueueBindings = (queues = useRuntimeConfig().cfJobs.queues) => validateJobQueueBindings(queues, jobs)',
    'export const assertQueueBindings = (queues = useRuntimeConfig().cfJobs.queues) => assertJobQueueBindings(queues, jobs)',
    '',
    'export function getQueue<const Job extends Jobs[number]>(',
    '  source: QueueSource | undefined,',
    '  job: Job,',
    ') {',
    '  const runtimeConfig = source && typeof source === \'object\' && \'context\' in source',
    '    ? useRuntimeConfig(source as never)',
    '    : useRuntimeConfig()',
    '  return createJobQueue(source, runtimeConfig.cfJobs.queues, job)',
    '}',
    '',
    'export function buildJobPayload<Name extends JobName>(name: Name, payload: JobPayload<Name>) {',
    '  return jobRegistry.buildPayload(name, payload as JobPayloadByName<Jobs, Name>)',
    '}',
    '',
    'export function prepareJob<Name extends JobName>(',
    '  opts: PrepareRegisteredDurableJobOptions<Jobs, Name>,',
    ') {',
    '  return prepareRegisteredDurableJob(jobRegistry, opts)',
    '}',
    '',
  ].join('\n')
}

async function resolveJobFiles(options: ModuleOptions, rootDir: string): Promise<string[]> {
  const dirs = toArray(options.jobsDir ?? 'server/jobs')
  const pattern = options.jobsPattern ?? '**/*.ts'
  const ignore = options.jobsIgnore ?? []
  const files = await Promise.all(dirs.map((dir) => {
    const resolvedDir = resolve(rootDir, dir)
    if (!existsSync(resolvedDir))
      return []
    return resolveFiles(resolvedDir, pattern, { ignore })
  }))
  return files.flat()
}

function isWatchedJobPath(path: string, options: ModuleOptions, rootDir: string): boolean {
  const dirs = toArray(options.jobsDir ?? 'server/jobs').map(dir => resolve(rootDir, dir))
  const absolutePath = resolve(rootDir, path)
  return dirs.some(dir => absolutePath.startsWith(dir))
}

function toArray<T>(value: T | T[]): T[] {
  return Array.isArray(value) ? value : [value]
}

function toImportPath(fromDir: string, file: string): string {
  const path = relative(fromDir, file).replace(/\\/g, '/').replace(/\.[cm]?tsx?$/, '')
  return path.startsWith('.') ? path : `./${path}`
}

function toJobName(file: string, options: ModuleOptions, rootDir: string): string {
  const jobDirs = toArray(options.jobsDir ?? 'server/jobs')
  const dirs = jobDirs
    .map(dir => resolve(rootDir, dir))
    .sort((a, b) => b.length - a.length)
  const dir = dirs.find(dir => file.startsWith(`${dir}/`) || file === dir)
  const fallbackDir = jobDirs[0] ?? 'server/jobs'
  const path = relative(dir ?? resolve(rootDir, fallbackDir), file)
    .replace(/\\/g, '/')
    .replace(/\.[cm]?tsx?$/, '')
  return path.replace(/\/index$/, '')
}
