import type { ModuleOptions } from './types'
import { existsSync } from 'node:fs'
import { relative, resolve, sep } from 'node:path'
import { addServerImports, addServerPlugin, addTemplate, createResolver, defineNuxtModule, resolveFiles, updateTemplates, useLogger } from '@nuxt/kit'
import {
  crossCheckWrangler,
  findWranglerConfig,
  parseWranglerConfig,
  renderSuggestedWranglerToml,
  type ModuleQueueExpectation,
} from './wrangler'

export type { ModuleOptions } from './types'

declare module '@nuxt/schema' {
  interface RuntimeConfig {
    cfJobs: { queues: ModuleOptions['queues'], defaultQueue?: string }
  }
}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: 'nuxt-cf-jobs',
    configKey: 'cfJobs',
  },
  defaults: {
    queues: {},
    jobsDir: 'server/jobs',
    jobsPattern: '**/*.ts',
    jobsIgnore: ['**/_*.ts', '**/*.d.ts', '**/*.test.ts', '**/*.spec.ts'],
    registryAlias: '#cf-jobs/app',
  },
  setup(options, nuxt) {
    const resolver = createResolver(import.meta.url)

    nuxt.options.alias['#cf-jobs/server'] = resolver.resolve('./runtime/server')
    addServerImports([
      { name: 'defineJob', from: resolver.resolve('./runtime/server/registry') },
    ])
    const registryTemplate = addTemplate({
      filename: 'cf-jobs/registry.ts',
      write: true,
      getContents: async () => generateRegistryTemplate(options, nuxt.options.rootDir, resolve(nuxt.options.buildDir, 'cf-jobs')),
    })
    nuxt.options.alias[options.registryAlias ?? '#cf-jobs/app'] = registryTemplate.dst

    nuxt.hooks.hook('builder:watch' as never, (async (_event: string, path: string) => {
      if (!isWatchedJobPath(path, options, nuxt.options.rootDir))
        return
      await updateTemplates({ filter: template => template.dst === registryTemplate.dst })
    }) as never)

    if (options.defaultQueue && !options.queues[options.defaultQueue])
      useLogger('nuxt-cf-jobs').warn(`cfJobs.defaultQueue="${options.defaultQueue}" is not a key of cfJobs.queues`)

    nuxt.options.runtimeConfig.cfJobs = {
      ...(nuxt.options.runtimeConfig.cfJobs ?? {}),
      queues: nuxt.options.runtimeConfig.cfJobs?.queues ?? options.queues,
      defaultQueue: nuxt.options.runtimeConfig.cfJobs?.defaultQueue ?? options.defaultQueue,
    }

    if (nuxt.options.dev)
      addServerPlugin(resolver.resolve('./runtime/server/plugins/dev-queues'))

    if (options.validateWrangler !== false)
      runWranglerCrossCheck(options, nuxt.options.rootDir, resolve(nuxt.options.buildDir, 'cf-jobs'))
  },
})

function runWranglerCrossCheck(options: ModuleOptions, rootDir: string, templateDir: string): void {
  const logger = useLogger('nuxt-cf-jobs')
  const wranglerPath = options.wranglerPath
    ? resolve(rootDir, options.wranglerPath)
    : findWranglerConfig(rootDir)

  const expectations: ModuleQueueExpectation[] = []
  for (const [logical, config] of Object.entries(options.queues ?? {})) {
    const binding = typeof config === 'string' ? config : config?.binding
    if (!binding)
      continue
    const cfQueueName = typeof config === 'object' && config?.queueName ? config.queueName : logical
    expectations.push({ logical, binding, cfQueueName })
  }

  if (expectations.length === 0)
    return

  // Always emit the suggested wrangler snippet so users can diff it.
  const suggested = renderSuggestedWranglerToml(expectations)
  addTemplate({
    filename: 'cf-jobs/wrangler.suggested.toml',
    write: true,
    getContents: () => suggested,
  })

  if (!wranglerPath) {
    logger.warn(`No wrangler.{toml,jsonc,json} found in ${rootDir}. See ${resolve(templateDir, 'wrangler.suggested.toml')} for the expected [[queues.producers]] / [[queues.consumers]] blocks.`)
    return
  }

  const wrangler = parseWranglerConfig(wranglerPath)
  const issues = crossCheckWrangler(wrangler, expectations)
  if (issues.length === 0)
    return

  const lines = issues.map(i => `  - [${i.logical}] ${i.reason}: ${i.detail}`)
  logger.warn(`nuxt-cf-jobs / wrangler config drift in ${wranglerPath}:\n${lines.join('\n')}\nSee ${resolve(templateDir, 'wrangler.suggested.toml')} for the expected blocks.`)
}

async function generateRegistryTemplate(options: ModuleOptions, rootDir: string, templateDir: string): Promise<string> {
  const files = await resolveJobFiles(options, rootDir)
  assertUniqueGeneratedJobNames(files, options, rootDir)
  const imports = files.map((file, index) => {
    return `import job${index} from ${JSON.stringify(toImportPath(templateDir, file))}`
  })
  const loaders = files.map((file) => {
    return `  ${JSON.stringify(toJobName(file, options, rootDir))}: () => import(${JSON.stringify(toImportPath(templateDir, file))}).then(m => m.default),`
  })
  const jobItems = files.map((_, index) => `job${index}`).join(', ')

  return [
    '/* This file is generated by nuxt-cf-jobs. Do not edit directly. */',
    `import { createCfJobsApp } from '#cf-jobs/server'`,
    `import { useRuntimeConfig } from '#imports'`,
    `import type { JobDefinitionsByNameOfLoaders, JobMessageByName, JobMessageByQueue, JobNameOf, JobPayloadByName, JobPayloadOf, JobQueueByName, QueueNameOf } from '#cf-jobs/server'`,
    `export type { QueueConsumerOptions } from '#cf-jobs/server'`,
    ...imports,
    '',
    'export const jobLoaders = {',
    ...loaders,
    '} as const',
    `export const jobs = [${jobItems}] as const`,
    `export const app = createCfJobsApp(jobs, useRuntimeConfig as never, { defaultQueue: ${options.defaultQueue ? JSON.stringify(options.defaultQueue) : 'undefined'} })`,
    'export const jobRegistry = app.jobRegistry',
    '',
    'export type Jobs = typeof jobs',
    'export type JobsByName = JobDefinitionsByNameOfLoaders<typeof jobLoaders>',
    'export type JobName = keyof JobsByName & JobNameOf<Jobs>',
    'export type JobDefinitionOf<Name extends JobName> = JobsByName[Name]',
    'export type QueueName = QueueNameOf<Jobs>',
    'export type JobPayload<Name extends JobName> = JobPayloadOf<JobDefinitionOf<Name>>',
    'export type JobQueue<Name extends JobName> = JobQueueByName<Jobs, Name>',
    'export type JobMessage<Name extends JobName> = JobMessageByName<Jobs, Name>',
    'export type QueueMessage<Queue extends QueueName> = JobMessageByQueue<Jobs, Queue>',
    '',
    'export const {',
    '  getHandler,',
    '  getJobDefinition,',
    '  getJobQueue,',
    '  getJobRoute,',
    '  validateRegistry,',
    '  validateQueueBindings,',
    '  assertQueueBindings,',
    '  getQueue,',
    '  buildJobPayload,',
    '  prepareJob,',
    '  registerQueueConsumer,',
    '} = app',
    '',
  ].join('\n')
}

async function resolveJobFiles(options: ModuleOptions, rootDir: string): Promise<string[]> {
  const dirs = toArray(options.jobsDir ?? 'server/jobs')
  const pattern = options.jobsPattern ?? '**/*.ts'
  const ignore = options.jobsIgnore ?? []
  const files = await Promise.all(dirs.map((dir) => {
    const resolvedDir = resolve(rootDir, dir)
    if (!existsSync(resolvedDir))
      return []
    return resolveFiles(resolvedDir, pattern, { ignore })
  }))
  return files.flat()
}

function assertUniqueGeneratedJobNames(files: string[], options: ModuleOptions, rootDir: string): void {
  const seen = new Map<string, string>()
  const duplicates: string[] = []
  for (const file of files) {
    const name = toJobName(file, options, rootDir)
    const previous = seen.get(name)
    if (previous)
      duplicates.push(`${name} (${previous}, ${file})`)
    else
      seen.set(name, file)
  }

  if (duplicates.length > 0)
    throw new Error(`Duplicate nuxt-cf-jobs generated job names: ${duplicates.join(', ')}`)
}

function isWatchedJobPath(path: string, options: ModuleOptions, rootDir: string): boolean {
  const dirs = toArray(options.jobsDir ?? 'server/jobs').map(dir => resolve(rootDir, dir))
  const absolutePath = resolve(rootDir, path)
  return dirs.some(dir => absolutePath === dir || absolutePath.startsWith(dir + sep))
}

function toArray<T>(value: T | T[]): T[] {
  return Array.isArray(value) ? value : [value]
}

function toImportPath(fromDir: string, file: string): string {
  const path = relative(fromDir, file).replace(/\\/g, '/').replace(/\.[cm]?tsx?$/, '')
  return path.startsWith('.') ? path : `./${path}`
}

function toJobName(file: string, options: ModuleOptions, rootDir: string): string {
  const jobDirs = toArray(options.jobsDir ?? 'server/jobs')
  const dirs = jobDirs
    .map(dir => resolve(rootDir, dir))
    .sort((a, b) => b.length - a.length)
  const dir = dirs.find(dir => file.startsWith(`${dir}/`) || file === dir)
  const fallbackDir = jobDirs[0] ?? 'server/jobs'
  const path = relative(dir ?? resolve(rootDir, fallbackDir), file)
    .replace(/\\/g, '/')
    .replace(/\.[cm]?tsx?$/, '')
  return path.replace(/\/index$/, '')
}
