name: Release

on:
  push:
    tags:
      - 'nuxt-cf-jobs-v*'
      - 'nuxt-use-query-v*'
      - 'nuxt-domain-events-v*'
      - 'nuxt-dx-v*'
      - 'nuxt-github-sponsors-v*'
      - 'nuxt-cloudflare-v*'

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
          package-manager-cache: false

      - run: npm install --global npm@11

      - run: pnpm install --frozen-lockfile

      - run: pnpm dev:prepare

      - run: pnpm lint

      - run: pnpm typecheck

      - run: pnpm test

      - run: pnpm test:pack

      - name: Publish nuxt-cf-jobs
        if: startsWith(github.ref_name, 'nuxt-cf-jobs-v')
        run: npm publish packages/nuxt-cf-jobs/.pack/*.tgz --access public

      - name: Publish nuxt-use-query
        if: startsWith(github.ref_name, 'nuxt-use-query-v')
        run: npm publish packages/nuxt-use-query/.pack/*.tgz --access public

      - name: Publish nuxt-domain-events
        if: startsWith(github.ref_name, 'nuxt-domain-events-v')
        run: npm publish packages/nuxt-domain-events/.pack/*.tgz --access public

      - name: Publish nuxt-dx
        if: startsWith(github.ref_name, 'nuxt-dx-v')
        run: npm publish packages/nuxt-dx/.pack/*.tgz --access public

      - name: Publish nuxt-github-sponsors
        if: startsWith(github.ref_name, 'nuxt-github-sponsors-v')
        run: npm publish packages/nuxt-github-sponsors/.pack/*.tgz --access public

      - name: Publish nuxt-cloudflare
        if: startsWith(github.ref_name, 'nuxt-cloudflare-v')
        run: npm publish packages/nuxt-cloudflare/.pack/*.tgz --access public
